### ISSUE TITLE
3D Stack Set

### ISSUE THREAD

**Issue by zekikus** [chcomin/pyvane#2]
Hi,

In your article there is a statement like this: "... were measured for a set of 324 3D stacks". I am a Ph.D. student and, I am working on automatic medical image segmentation with meta-heuristic algorithms. I need 3D stack images for my work. Can you share 3D Stacks images?

Thank you,

Best Regards

**Comment by chcomin** [comment]
Sorry, we cannot share the full 3D dataset. But we have made available a much more diverse set of samples that are similar to the ones used in the article:

VessMAP - Feature-Mapped Cortex Vasculature Dataset
https://zenodo.org/records/10045265
